-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6kRRtsEQaPBS4dAK
S38sVNCqP9mR8df4DrjOD9cZgMCgCgYIKoZIzj0DAQehRANCAASkTZlz3Znx3XJg
5jPFl/6brVx8zbuZjPDbCat5D6lfNmwJtILXCQhH9XGkjymbpBhr2mLpVS9mrDfq
+/sAXBIp
-----END PRIVATE KEY-----