export enum SearchActionTypes {
  SET_AUTO_COMPLETE_SESSION_ID = "SET_AUTO_COMPLETE_SESSION_ID",

  //Destination search results
  SET_DESTINATION_SEARCH_LOADING = "SET_DESTINATION_SEARCH_LOADING",
  SET_DESTINATION_TYPE = "SET_DESTINATION_TYPE",
  SET_DESTINATIONS = "SET_DESTINATIONS",
  ADD_CACHED_DESTINATION = "ADD_CACHED_DESTINATION",
  REMOVE_FIRST_CACHED_DESTINATION = "REMOVE_FIRST_CACHED_DESTINATION",
  SET_DESTINATION_DETAILS = "SET_DESTINATION_DETAILS",

  //Adds origin from auto complete input
  ADD_ORIGIN = "ADD_ORIGIN",
  REMOVE_ORIGIN_INDEX = "REMOVE_ORIGIN_INDEX",
  SET_ORIGIN_INDEX = "SET_ORIGIN_INDEX",

  //Currently selected destination index
  SET_DESTINATION_INDEX = "SET_DESTINATION_INDEX",

  //Directions
  GET_ROUTE_GEOMETRIES = "GET_ROUTE_GEOMETRIES",
  SET_ROUTES_LOADING = "SET_ROUTES_LOADING",
  ADD_ROUTE_GEOMETRY = "ADD_ROUTE_GEOMETRY",
  CLEAR_ROUTE_GEOMETRIES = "CLEAR_ROUTE_GEOMETRIES",
  ADD_CACHED_ROUTE_GEOMETRY = "ADD_CACHED_ROUTE_GEOMETRY",
  REMOVE_FIRST_CACHED_ROUTE_GEOMETRY = "REMOVE_FIRST_CACHED_ROUTE_GEOMETRY",

  //Clear data
  LOGOUT_USER = "LOGOUT_USER",

  //User location
  SET_USER_LOCATION = "SET_USER_LOCATION",
}
