desc "Build a Release build & upload to Firebase App Distribution"
lane :app_distribution do

app_store_connect_api_key(
    key_id: "78WD9684HN",
    issuer_id: "7221ae1d-9214-4a31-8150-4a10d427907a",
    key_content: ENV['APP_STORE_CONNECT_KEY'],
)
create_keychain(
    name: "CI",
    password: ENV["MATCH_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
)
# Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
# pilot
match(type: 'adhoc', app_identifier: ['com.inBetween'], keychain_name: "CI", keychain_password: ENV["MATCH_PASSWORD"])
gym(
   workspace: './ios/Between.xcworkspace',
   scheme: 'Between',
   configuration: 'Release',
   clean: true,
   output_directory: 'archives',
   output_name: 'Between.ipa',
   export_method: 'ad-hoc'
)
firebase_app_distribution(
     app: ENV['FIREBASE_APP_ID'],
     firebase_cli_token: ENV["FIREBASE_TOKEN"],
     groups: 'devs',
     release_notes: 'new release, check it out!',
     firebase_cli_path: '/usr/local/bin/firebase',
     ipa_path: 'archives/Between.ipa'
)
end