name: Pipeline

on:
  push:
    branches:
    - prettierAction

env:
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
 


jobs:
  build:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Ruby
        working-directory: ./ios
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Setup Fastlane
        run: bundle install
      - name: install Node dependencies
        run: npm install
      - name: Build with Fastlane
        working-directory: ./ios
        run: bundle exec fastlane app_distribution 